# Generated by Django 3.0.6 on 2021-05-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock', '0004_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='equip',
            field=models.ManyToManyField(help_text='Оборудование', to='lock.Equipment'),
        ),
    ]
